# Generated by Django 4.1.7 on 2024-07-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dj_answer", models.CharField(max_length=1023, null=True)),
                ("alc_answer", models.CharField(max_length=1023, null=True)),
                ("sql_answer", models.CharField(max_length=1023, null=True)),
            ],
            options={
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q_no", models.IntegerField()),
                ("q_text", models.CharField(max_length=255)),
                (
                    "database",
                    models.CharField(
                        choices=[("IN", "Inventory")], default=None, max_length=2
                    ),
                ),
            ],
            options={
                "db_table": "question",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dj_answer", models.CharField(max_length=1023, null=True)),
                ("alc_answer", models.CharField(max_length=1023, null=True)),
                ("sql_answer", models.CharField(max_length=1023, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
            ],
            options={
                "db_table": "solution",
            },
        ),
    ]
