# Generated by Django 4.2.14 on 2024-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="alc_answer",
            field=models.TextField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="dj_answer",
            field=models.TextField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="sql_answer",
            field=models.TextField(max_length=1023, null=True),
        ),
    ]
