# Generated by Django 4.2.14 on 2024-10-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_answer_alc_answer_alter_answer_dj_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="q_slug",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="database",
            field=models.CharField(
                choices=[("in", "Inventory")], default=None, max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s_question",
                to="core.question",
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AnswerCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dj_check", models.TextField(max_length=1023, null=True)),
                ("alc_check", models.TextField(max_length=1023, null=True)),
                ("sql_check", models.TextField(max_length=1023, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ac_question",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "db_table": "anscheck",
            },
        ),
    ]
