# Generated by Django 4.1.7 on 2024-07-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("grade", models.IntegerField()),
            ],
            options={
                "db_table": "inventory_customer",
            },
        ),
        migrations.CreateModel(
            name="Salesman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("commission", models.FloatField()),
            ],
            options={
                "db_table": "inventory_salesman",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="dbmodels.customer",
                    ),
                ),
                (
                    "salesman_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="o_salesmen",
                        to="dbmodels.salesman",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_order",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="salesman_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="c_salesmen",
                to="dbmodels.salesman",
            ),
        ),
    ]
