# Generated by Django 4.2.14 on 2024-10-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dbmodels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="o_customer",
                to="dbmodels.customer",
            ),
        ),
    ]
