# Generated by Django 4.2.14 on 2024-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
    ]
